name: Generate file index

on:
  push:
    paths:
      - 'f/**'
      - '.github/workflows/generate-file-index.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate file index
        run: |
          echo "Generating file index"
          echo "[" > f/index.json

          files=($(find f -type f -not -name "index.json" | sort))
          echo "${#files[@]} files found"

          for i in ${!files[@]}; do
            path=$(echo "${files[$i]}" | sed 's|^f/||')
            size=$(stat -c %s "${files[$i]}")
            birth=$(stat -c %y "${files[$i]}" | cut -d '.' -f 1)
            modify=$(stat -c %w "${files[$i]}" | cut -d '.' -f 1)

            if [ "$i" != 0 ]; then
              echo "," >> f/index.json
            fi

            echo "Adding $path"
            echo "  {" >> f/index.json
            echo "    \"file\": \"${path}\"," >> f/index.json
            echo "    \"size\": ${size}," >> f/index.json
            echo "    \"birth\": \"${birth}\"," >> f/index.json
            echo "    \"modify\": \"${modify}\"" >> f/index.json
            echo "  }" >> f/index.json
            echo "Successfully added $path"
          done

          echo "]" >> f/index.json

          cat f/index.json
      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add f/index.json
          git commit -m "Update file index"
          git push
